package com.waibao.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomer<M extends BaseCustomer<M>> extends Model<M> implements IBean {

	public void setCustomerId(java.lang.Integer customerId) {
		set("customerId", customerId);
	}

	public java.lang.Integer getCustomerId() {
		return get("customerId");
	}

	public void setCustomerName(java.lang.String customerName) {
		set("customerName", customerName);
	}

	public java.lang.String getCustomerName() {
		return get("customerName");
	}

	public void setCustomerSex(java.lang.Integer customerSex) {
		set("customerSex", customerSex);
	}

	public java.lang.Integer getCustomerSex() {
		return get("customerSex");
	}

	public void setCustomerAge(java.lang.Integer customerAge) {
		set("customerAge", customerAge);
	}

	public java.lang.Integer getCustomerAge() {
		return get("customerAge");
	}

	public void setCustomerNo(java.lang.String customerNo) {
		set("customerNo", customerNo);
	}

	public java.lang.String getCustomerNo() {
		return get("customerNo");
	}

	public void setCustomerAddress(java.lang.String customerAddress) {
		set("customerAddress", customerAddress);
	}

	public java.lang.String getCustomerAddress() {
		return get("customerAddress");
	}

	public void setCustomerNote(java.lang.String customerNote) {
		set("customerNote", customerNote);
	}

	public java.lang.String getCustomerNote() {
		return get("customerNote");
	}

	public void setCustomerGrade(java.lang.Integer customerGrade) {
		set("customerGrade", customerGrade);
	}

	public java.lang.Integer getCustomerGrade() {
		return get("customerGrade");
	}

	public void setStaffId(java.lang.String staffId) {
		set("staffId", staffId);
	}

	public java.lang.String getStaffId() {
		return get("staffId");
	}

	public void setInsertDate(java.util.Date insertDate) {
		set("insertDate", insertDate);
	}

	public java.util.Date getInsertDate() {
		return get("insertDate");
	}

	public void setInsertUserId(java.lang.String insertUserId) {
		set("insertUserId", insertUserId);
	}

	public java.lang.String getInsertUserId() {
		return get("insertUserId");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("updateDate", updateDate);
	}

	public java.util.Date getUpdateDate() {
		return get("updateDate");
	}

	public void setUpdateUserId(java.lang.String updateUserId) {
		set("updateUserId", updateUserId);
	}

	public java.lang.String getUpdateUserId() {
		return get("updateUserId");
	}

	public void setVersion(java.lang.String version) {
		set("version", version);
	}

	public java.lang.String getVersion() {
		return get("version");
	}

}
