package com.waibao.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("ttpm_buy", "buyId", Buy.class);
		arp.addMapping("ttpm_customer", "customerId", Customer.class);
		arp.addMapping("ttpm_product", "productId", Product.class);
		arp.addMapping("ttpm_staff", "staffId", Staff.class);
		arp.addMapping("ttpm_user", "username", User.class);
	}
}

