package com.waibao.common.model;

import com.waibao.common.model.base.BaseBuy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Buy extends BaseBuy<Buy> {
	public static final Buy dao = new Buy();
}
