package com.waibao.common.model;

import java.util.ArrayList;
import java.util.List;

import com.jfinal.plugin.activerecord.Page;
import com.waibao.common.model.base.BaseStaff;
import com.waibao.utils.StringUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Staff extends BaseStaff<Staff> {
	public static final Staff dao = new Staff();
	
	public Page<Staff> query(int pageNumber, int pageSize, String name, String phone){
		List<Object> params = new ArrayList<Object>(2);
		String sql="from ttpm_staff where 1=1";
		if(StringUtils.isNotEmpty(name)){
			sql+=" and staffName like ?";
			params.add("%"+name+"%");
		}
		if(StringUtils.isNotEmpty(phone)){
			sql+=" and staffPhone like ?";
			params.add("%"+phone+"%");
		}		
		return this.paginate(pageNumber, pageSize, "select *", sql, params.toArray());
	}
}
